# TO DO:
# - ExeutionRoleArn in task def how to get this ARN?
# - Security groups had var $SG_ID but no SG_ID defined anywhere only SG_NAME

name: Create Preview App

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened]

env:
  PROJECT: ${{ github.event.repository.name }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  PR_NUMBER: ${{ github.event.number }}
  DOMAIN: feedback-interface.icyntkt.xyz/ # OurApp Subdomain
  AWS_REGION: us-east-2 # REGION
  ECR_REPOSITORY: team5-client-app-test3 # IMAGE_REPOSITORY
  ECS_CLUSTER: team5-client-app3-cluster # CLUSTER_NAME
  PORT: 5173 # PORT
  ROLE_ARN: arn:aws:iam::126480444030:role/ecsTaskExecutionRole # EXECUTION_ROLE_ARN
  SUBNET_NAME: subnet-01cef9a94723b1c34 # DEFAULT_SUBNET
  SG_NAME: sg-0dd59509b20ad0cfd # SECURITY_GROUP

permissions: {}

jobs:
  notify_start:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/post-comment@v1
        with:
          message: "| Status | Message |\n|--------|-------|\n| \U00002692 | Your preview app is currently being built and deployed to AWS |"
          append: false

  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_ID }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Define task definition and deploy to Amazon ECS
        uses: ./.github/actions/deploy_preview@v1

  notify_end:
    runs-on: ubuntu-latest
    needs: deploy_app
    steps:
      - uses: ./.github/actions/post-comment@v1
        with:
          message: "| \U00002705 | Yay! Visit your super cool amazing preview app here ${{ needs.deploy_app.outputs.url }} |"
          append: true
